
sec_name = "Period 7 Elements"

electronegativity = {
    "Francium (Fr)": 0.7,
    "Radium (Ra)": 0.9,
    "Actinium (Ac)": 1.1,
    "Thorium (Th)": 1.3,
    "Protactinium (Pa)": 1.5,
    "Uranium (U)": 1.38,
    "Neptunium (Np)": 1.36,
    "Plutonium (Pu)": 1.28,
    "Americium (Am)": 1.3,
    "Curium (Cm)": 1.3,
    "Berkelium (Bk)": 1.3,
    "Californium (Cf)": 1.3,
    "Einsteinium (Es)": 1.3,
    "Fermium (Fm)": 1.3,
    "Mendelevium (Md)": 1.3,
    "Nobelium (No)": 1.3,
    "Lawrencium (Lr)": 1.3,
    "Rutherfordium (Rf)": 1.3,
    "Dubnium (Db)": 1.3,
    "Seaborgium (Sg)": 1.3,
    "Bohrium (Bh)": 1.3,
    "Hassium (Hs)": 1.3,
    "Meitnerium (Mt)": 1.3,
    "Darmstadtium (Ds)": 1.3,
    "Roentgenium (Rg)": 1.3,
    "Copernicium (Cn)": 1.3,
    "Nihonium (Nh)": 1.3,
    "Flerovium (Fl)": 1.3,
    "Moscovium (Mc)": 1.3,
    "Livermorium (Lv)": 1.3,
    "Tennessine (Ts)": 1.3,
    "Oganesson (Og)": 1.3
}


# atomic radii in Angstroms
atomic_radii = {
    "Francium (Fr)": 2.6,
    "Radium (Ra)": 2.21,
    "Actinium (Ac)": 1.95,
    "Thorium (Th)": 1.8,
    "Protactinium (Pa)": 1.8,
    "Uranium (U)": 1.75,
    "Neptunium (Np)": 1.75,
    "Plutonium (Pu)": 1.75,
    "Americium (Am)": 1.73,
    "Curium (Cm)": 1.73,
    "Berkelium (Bk)": 1.72,
    "Californium (Cf)": 1.7,
    "Einsteinium (Es)": 1.7,
    "Fermium (Fm)": 1.7,
    "Mendelevium (Md)": 1.7,
    "Nobelium (No)": 1.7,
    "Lawrencium (Lr)": 1.7,
    "Rutherfordium (Rf)": 1.7,
    "Dubnium (Db)": 1.7,
    "Seaborgium (Sg)": 1.7,
    "Bohrium (Bh)": 1.7,
    "Hassium (Hs)": 1.7,
    "Meitnerium (Mt)": 1.7,
    "Darmstadtium (Ds)": 1.7,
    "Roentgenium (Rg)": 1.7,
    "Copernicium (Cn)": 1.7,
    "Nihonium (Nh)": 1.7,
    "Flerovium (Fl)": 1.7,
    "Moscovium (Mc)": 1.7,
    "Livermorium (Lv)": 1.7,
    "Tennessine (Ts)": 1.7,
    "Oganesson (Og)": 1.7
}


# density in g/cm^3
density = {
    "Francium (Fr)": 1.87,
    "Radium (Ra)": 5.5,
    "Actinium (Ac)": 10.07,
    "Thorium (Th)": 11.72,
    "Protactinium (Pa)": 15.37,
    "Uranium (U)": 18.95,
    "Neptunium (Np)": 20.45,
    "Plutonium (Pu)": 19.84,
    "Americium (Am)": 13.67,
    "Curium (Cm)": 13.51,
    "Berkelium (Bk)": 14.78,
    "Californium (Cf)": 15.1,
    "Einsteinium (Es)": 13.5,
    "Fermium (Fm)": 15.1,
    "Mendelevium (Md)": 16,
    "Nobelium (No)": 18.1,
    "Lawrencium (Lr)": 15.6,
    "Rutherfordium (Rf)": 18.1,
    "Dubnium (Db)": 29.3,
    "Seaborgium (Sg)": 35,
    "Bohrium (Bh)": 37.1,
    "Hassium (Hs)": 40.7,
    "Meitnerium (Mt)": 37.4,
    "Darmstadtium (Ds)": 34.8,
    "Roentgenium (Rg)": 28.7,
    "Copernicium (Cn)": 23.7,
    "Nihonium (Nh)": 16,
    "Flerovium (Fl)": 14,
    "Moscovium (Mc)": 13.5,
    "Livermorium (Lv)": 12.9,
    "Tennessine (Ts)": 7.17,
    "Oganesson (Og)": 4.9
}

# in Kelvin
melting_point = {
    "Francium (Fr)": 300,
    "Radium (Ra)": 973,
    "Actinium (Ac)": 1323,
    "Thorium (Th)": 2023,
    "Protactinium (Pa)": 1841,
    "Uranium (U)": 1408,
    "Neptunium (Np)": 913,
    "Plutonium (Pu)": 913,
    "Americium (Am)": 1449,
    "Curium (Cm)": 1613,
    "Berkelium (Bk)": 1323,
    "Californium (Cf)": 1173,
    "Einsteinium (Es)": 1133,
    "Fermium (Fm)": 1800,
    "Mendelevium (Md)": 1100,
    "Nobelium (No)": 1100,
    "Lawrencium (Lr)": 1900,
    "Rutherfordium (Rf)": 2400,
    "Dubnium (Db)": 0,
    "Seaborgium (Sg)": 0,
    "Bohrium (Bh)": 0,
    "Hassium (Hs)": 0,
    "Meitnerium (Mt)": 0,
    "Darmstadtium (Ds)": 0,
    "Roentgenium (Rg)": 0,
    "Copernicium (Cn)": 0,
    "Nihonium (Nh)": 700,
    "Flerovium (Fl)": 340,
    "Moscovium (Mc)": 0,
    "Livermorium (Lv)": 0,
    "Tennessine (Ts)": 0,
    "Oganesson (Og)": 0
}


# in K
boiling_point = {
    "Francium (Fr)": 950,
    "Radium (Ra)": 2010,
    "Actinium (Ac)": 3500,
    "Thorium (Th)": 5061,
    "Protactinium (Pa)": 4300,
    "Uranium (U)": 4404,
    "Neptunium (Np)": 4273,
    "Plutonium (Pu)": 3505,
    "Americium (Am)": 2880,
    "Curium (Cm)": 3383,
    "Berkelium (Bk)": 983,
    "Californium (Cf)": 1173,
    "Einsteinium (Es)": 0,
    "Fermium (Fm)": 0,
    "Mendelevium (Md)": 0,
    "Nobelium (No)": 0,
    "Lawrencium (Lr)": 0,
    "Rutherfordium (Rf)": 0,
    "Dubnium (Db)": 0,
    "Seaborgium (Sg)": 0,
    "Bohrium (Bh)": 0,
    "Hassium (Hs)": 0,
    "Meitnerium (Mt)": 0,
    "Darmstadtium (Ds)": 0,
    "Roentgenium (Rg)": 0,
    "Copernicium (Cn)": 0,
    "Nihonium (Nh)": 0,
    "Flerovium (Fl)": 0,
    "Moscovium (Mc)": 0,
    "Livermorium (Lv)": 0,
    "Tennessine (Ts)": 0,
    "Oganesson (Og)": 0
}

